/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import napakalaki.Monster;

/**
 *
 * @author Carlos de al Torre
 */
public class MosterView extends javax.swing.JPanel {

    /**
     * Este será el objeto de tipo monstruo que tengamos en la vista
     * para preguntarle todos los datos necesarios.
     */
    Monster monsterModel;
    
    /**
     * Creates new form MosterView
     */
    public MosterView() {
        initComponents();
    }

    /**
     * Con este metodo conseguimos asignar el monstruo a la vista para mostrar
     * todos sus atributos.
     * @param aMonster Este es el objeto tipo monster que nos da el controlador.
     */
    public void setMonster(Monster aMonster){
        this.monsterModel = aMonster;

        this.badConsequenceView.setBadConsequence(this.monsterModel.getBadConsequence());
        this.prizeView.setPrize(this.monsterModel.getPrize());
        repaint();
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        badConsequenceView = new gui.BadConsequenceView();
        prizeView = new gui.PrizeView();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Espacio del Monstruo"));
        setMinimumSize(new java.awt.Dimension(885, 250));
        setPreferredSize(new java.awt.Dimension(885, 250));

        javax.swing.GroupLayout badConsequenceViewLayout = new javax.swing.GroupLayout(badConsequenceView);
        badConsequenceView.setLayout(badConsequenceViewLayout);
        badConsequenceViewLayout.setHorizontalGroup(
            badConsequenceViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );
        badConsequenceViewLayout.setVerticalGroup(
            badConsequenceViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout prizeViewLayout = new javax.swing.GroupLayout(prizeView);
        prizeView.setLayout(prizeViewLayout);
        prizeViewLayout.setHorizontalGroup(
            prizeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        prizeViewLayout.setVerticalGroup(
            prizeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(473, Short.MAX_VALUE)
                .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(badConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(badConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.BadConsequenceView badConsequenceView;
    private gui.PrizeView prizeView;
    // End of variables declaration//GEN-END:variables
}
