package gui;

import java.awt.Toolkit;
import napakalaki.Napakalaki;
import napakalaki.Player;
import napakalaki.Treasure;

/**
 *
 * @author Carlos de al Torre
 */
public class NapakalakiView extends javax.swing.JFrame {

    /**
     * Este será el modelo de la aplicacion es donde están las 
     * funcionalidades del programa
     */
    Napakalaki napakalakiModel;
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
        // Con esto conseguimos que siempre aparezca en el centro de la pantalla
        int ancho = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth()/2-this.getWidth()/2;
        int alto = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight()/2-this.getHeight()/2;
        setBounds(ancho, alto,this.getWidth(),this.getHeight());
    }

    public void setNapakalaki(Napakalaki napa){
        this.napakalakiModel = napa;
        this.playerView.setPlayer(this.napakalakiModel.getCurrentPlayer());
        this.mosterView.setMonster(this.napakalakiModel.getCurrentMonster());
        repaint();
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerView = new gui.PlayerView();
        jBConocerMonstruo = new javax.swing.JButton();
        jBDarseGolpes = new javax.swing.JButton();
        jBSiguienteTurno = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jPEstadoCombate = new javax.swing.JPanel();
        mosterView = new gui.MosterView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego Napakalaki");
        setMinimumSize(new java.awt.Dimension(920, 925));
        setName("principal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(920, 925));

        jBConocerMonstruo.setText("Conocel el Monstruo");

        jBDarseGolpes.setText("Darse Golpes");

        jBSiguienteTurno.setText("Siguiente Turno");

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jPEstadoCombate.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado del Combate"));

        javax.swing.GroupLayout jPEstadoCombateLayout = new javax.swing.GroupLayout(jPEstadoCombate);
        jPEstadoCombate.setLayout(jPEstadoCombateLayout);
        jPEstadoCombateLayout.setHorizontalGroup(
            jPEstadoCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );
        jPEstadoCombateLayout.setVerticalGroup(
            jPEstadoCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jBConocerMonstruo)
                                .addGap(18, 18, 18)
                                .addComponent(jBDarseGolpes)
                                .addGap(18, 18, 18)
                                .addComponent(jBSiguienteTurno)
                                .addGap(323, 323, 323)
                                .addComponent(jBSalir))
                            .addComponent(playerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPEstadoCombate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mosterView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mosterView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPEstadoCombate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConocerMonstruo)
                    .addComponent(jBDarseGolpes)
                    .addComponent(jBSiguienteTurno)
                    .addComponent(jBSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConocerMonstruo;
    private javax.swing.JButton jBDarseGolpes;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBSiguienteTurno;
    private javax.swing.JPanel jPEstadoCombate;
    private gui.MosterView mosterView;
    private gui.PlayerView playerView;
    // End of variables declaration//GEN-END:variables
}
