package gui;

import napakalaki.BadConsequence;

/**
 *
 * @author Carlos de al Torre
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {

    /**
     * Este será el objeto de tipo BadConsequence que tengamos en la vista
     * para preguntarle todos los datos necesarios.
     */
    BadConsequence pendingbadconsequenceModel;
    
    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
    }

    /**
     * Con este metodo conseguimos asignar el BadConsequence a la vista
     * para mostrar todos sus atributos.
     * @param aBadConsequence es un objeto de cualquiera de las clases que
     * hay de BadConsequence, ya que lo leera igualmente.
     */
    protected void setPendingBadConsequence(BadConsequence aBadConsequence){
        this.pendingbadconsequenceModel = aBadConsequence;
        
        repaint();
        revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder("Mal Rollo Pendiente"));
        setMinimumSize(new java.awt.Dimension(222, 230));
        setPreferredSize(new java.awt.Dimension(222, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
