package gui;

import java.util.ArrayList;
import napakalaki.CultistPlayer;
import napakalaki.Player;
import napakalaki.Treasure;

/**
 *
 * @author Carlos de al Torre
 */
public class PlayerView extends javax.swing.JPanel {

    /**
     * Este es el jugador que contiene todos los datos que se mostrarán en la
     * vista.
     */
    Player playerModel;

    /**
     * Creamos un Objeto de tipo Jugador para la vista.
     */
    public PlayerView() {
        initComponents();
        this.jLBonusBasico.setVisible(false);
        this.jLBonusEspecial.setVisible(false);
        this.jTBonusBasico.setVisible(false);
        this.jTBonusEspecial.setVisible(false);
        this.pendingBadConsequenceView.setVisible(false);
    }

    /**
     * Con esto conseguimos que se puedan mostrar los diferentes tesoros en
     *
     * @param aPanel
     * @param aList
     */
    private void fillTreasurePanel(javax.swing.JPanel aPanel, ArrayList<Treasure> aList) {
        // Se elimina la información antigua, si la hubiera
        aPanel.removeAll();
        // Se recorre la lista de tesoros construyendo y añadiendo sus vistas
        // al aPanel
        for (Treasure t : aList) {
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure(t);
            aTreasureView.setVisible(true);
            aPanel.add(aTreasureView);
        }
        // Se fuerza la actualización visual del panel
        aPanel.repaint();
        aPanel.revalidate();
    }

    /**
     * Con esto asignamos el jugador correspondiente a la parte de la fista del
     * jugador con todos sus datos.
     *
     * @param aPlayer este es el objeto jugador del modelo.
     */
    protected void setPlayer(Player aPlayer) {
        this.playerModel = aPlayer;
        this.jTNombreJugador.setText(this.playerModel.getName());
        this.jTEnemigo.setText(this.playerModel.getEnemy().getName());
        this.jTNivelJugador.setText("" + this.playerModel.getLevels());
        if (this.playerModel instanceof CultistPlayer) {
            this.jCBJugadorSectario.setSelected(true);
            this.jLBonusBasico.setVisible(true);
            this.jLBonusEspecial.setVisible(true);
            this.jTBonusBasico.setVisible(true);
            this.jTBonusEspecial.setVisible(true);
            this.jTBonusBasico.setText("" + ((CultistPlayer) this.playerModel).getMyCultistCard().getBasicValue());
            this.jTBonusEspecial.setText("" + ((CultistPlayer) this.playerModel).getMyCultistCard().getSpecialValue());
        } else {
            this.jCBJugadorSectario.setSelected(false);
            this.jLBonusBasico.setVisible(false);
            this.jLBonusEspecial.setVisible(false);
            this.jTBonusBasico.setVisible(false);
            this.jTBonusEspecial.setVisible(false);
        }
        if (this.playerModel.getPendingBadConsequence() != null && !this.playerModel.getPendingBadConsequence().isEmpty()) {
            this.pendingBadConsequenceView.setPendingBadConsequence(this.playerModel.getPendingBadConsequence());
            this.pendingBadConsequenceView.setVisible(true);
        } else {
            this.pendingBadConsequenceView.setVisible(false);
        }
        this.fillTreasurePanel(jPTesorosVisibles, this.playerModel.getVisibleTreasures());
        this.fillTreasurePanel(jPTesorosOcultos, this.playerModel.getHiddenTreasures());
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTesorosOcultos = new javax.swing.JPanel();
        jPTesorosVisibles = new javax.swing.JPanel();
        jPDatosJugador = new javax.swing.JPanel();
        jLNombreJugador = new javax.swing.JLabel();
        jLEnemigo = new javax.swing.JLabel();
        jTNombreJugador = new javax.swing.JTextField();
        jTEnemigo = new javax.swing.JTextField();
        jLNivelJugador = new javax.swing.JLabel();
        jTNivelJugador = new javax.swing.JTextField();
        jLJugadorSectario = new javax.swing.JLabel();
        jCBJugadorSectario = new javax.swing.JCheckBox();
        jLBonusBasico = new javax.swing.JLabel();
        jTBonusBasico = new javax.swing.JTextField();
        jLBonusEspecial = new javax.swing.JLabel();
        jTBonusEspecial = new javax.swing.JTextField();
        jBEquiparTesoro = new javax.swing.JButton();
        jBDescartarTesoro = new javax.swing.JButton();
        jBRobarTesoro = new javax.swing.JButton();
        jBDescartarTodos = new javax.swing.JButton();
        pendingBadConsequenceView = new gui.PendingBadConsequenceView();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Espacio del Jugador"));

        jPTesorosOcultos.setBorder(javax.swing.BorderFactory.createTitledBorder("Tesoros Ocultos"));
        jPTesorosOcultos.setToolTipText("Estos son los tesoros que NO tiene equipados el jugador");
        jPTesorosOcultos.setMinimumSize(new java.awt.Dimension(645, 230));
        jPTesorosOcultos.setName("jPTesorosOcultos"); // NOI18N
        jPTesorosOcultos.setPreferredSize(new java.awt.Dimension(645, 230));

        jPTesorosVisibles.setBorder(javax.swing.BorderFactory.createTitledBorder("Tesoros Visibles"));
        jPTesorosVisibles.setToolTipText("Estos son los tesoros que tiene equipados el jugador");
        jPTesorosVisibles.setMinimumSize(new java.awt.Dimension(645, 230));
        jPTesorosVisibles.setName("jPTesorosVisibles"); // NOI18N
        jPTesorosVisibles.setPreferredSize(new java.awt.Dimension(645, 230));

        jPDatosJugador.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Jugador"));
        jPDatosJugador.setMinimumSize(new java.awt.Dimension(222, 230));
        jPDatosJugador.setPreferredSize(new java.awt.Dimension(222, 230));

        jLNombreJugador.setLabelFor(jTNombreJugador);
        jLNombreJugador.setText("Nombre:");
        jLNombreJugador.setName("jLNombreJugador"); // NOI18N

        jLEnemigo.setLabelFor(jTEnemigo);
        jLEnemigo.setText("Enemigo:");
        jLEnemigo.setToolTipText("");
        jLEnemigo.setName("jLEnemigo"); // NOI18N

        jTNombreJugador.setEditable(false);
        jTNombreJugador.setText("jTNombreJugador");
        jTNombreJugador.setBorder(null);

        jTEnemigo.setEditable(false);
        jTEnemigo.setText("jTEnemigo");
        jTEnemigo.setBorder(null);

        jLNivelJugador.setLabelFor(jTNivelJugador);
        jLNivelJugador.setText("Nivel:");
        jLNivelJugador.setToolTipText("");
        jLNivelJugador.setName("jLNivelJugador"); // NOI18N

        jTNivelJugador.setEditable(false);
        jTNivelJugador.setText("jTNivelJugador");
        jTNivelJugador.setBorder(null);

        jLJugadorSectario.setLabelFor(jCBJugadorSectario);
        jLJugadorSectario.setText("Jugador Sectario:");
        jLJugadorSectario.setToolTipText("");
        jLJugadorSectario.setName("jLJugadorSectario"); // NOI18N

        jCBJugadorSectario.setEnabled(false);
        jCBJugadorSectario.setName("jCBJugadorSectario"); // NOI18N

        jLBonusBasico.setLabelFor(jTBonusBasico);
        jLBonusBasico.setText("Bonus Basico:");
        jLBonusBasico.setName("jLBonusBasico"); // NOI18N

        jTBonusBasico.setEditable(false);
        jTBonusBasico.setText("jTBonusBasico");
        jTBonusBasico.setBorder(null);

        jLBonusEspecial.setLabelFor(jTBonusEspecial);
        jLBonusEspecial.setText("Bonus Especial:");
        jLBonusEspecial.setName("jLBonus"); // NOI18N

        jTBonusEspecial.setEditable(false);
        jTBonusEspecial.setText("jTBonusEspecial");
        jTBonusEspecial.setBorder(null);

        javax.swing.GroupLayout jPDatosJugadorLayout = new javax.swing.GroupLayout(jPDatosJugador);
        jPDatosJugador.setLayout(jPDatosJugadorLayout);
        jPDatosJugadorLayout.setHorizontalGroup(
            jPDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosJugadorLayout.createSequentialGroup()
                .addComponent(jLJugadorSectario)
                .addGap(18, 18, 18)
                .addComponent(jCBJugadorSectario)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPDatosJugadorLayout.createSequentialGroup()
                    .addGroup(jPDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLNombreJugador)
                        .addComponent(jLEnemigo)
                        .addComponent(jLNivelJugador))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTEnemigo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTNivelJugador)
                        .addComponent(jTNombreJugador)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDatosJugadorLayout.createSequentialGroup()
                    .addGroup(jPDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLBonusBasico)
                        .addComponent(jLBonusEspecial))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTBonusEspecial, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(jTBonusBasico, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
        );
        jPDatosJugadorLayout.setVerticalGroup(
            jPDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosJugadorLayout.createSequentialGroup()
                .addGroup(jPDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombreJugador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTEnemigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEnemigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNivelJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNivelJugador))
                .addGap(18, 18, 18)
                .addGroup(jPDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLJugadorSectario)
                    .addComponent(jCBJugadorSectario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBonusBasico)
                    .addComponent(jTBonusBasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBonusEspecial)
                    .addComponent(jTBonusEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBEquiparTesoro.setText("Equipar Tesoro");

        jBDescartarTesoro.setText("Descartar Tesoro");

        jBRobarTesoro.setText("Robar Tesoro");

        jBDescartarTodos.setText("Descartar Todos");

        javax.swing.GroupLayout pendingBadConsequenceViewLayout = new javax.swing.GroupLayout(pendingBadConsequenceView);
        pendingBadConsequenceView.setLayout(pendingBadConsequenceViewLayout);
        pendingBadConsequenceViewLayout.setHorizontalGroup(
            pendingBadConsequenceViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );
        pendingBadConsequenceViewLayout.setVerticalGroup(
            pendingBadConsequenceViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jBEquiparTesoro)
                .addGap(18, 18, 18)
                .addComponent(jBDescartarTesoro)
                .addGap(18, 18, 18)
                .addComponent(jBDescartarTodos)
                .addGap(18, 18, 18)
                .addComponent(jBRobarTesoro)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPDatosJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pendingBadConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPTesorosVisibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPTesorosOcultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPDatosJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPTesorosVisibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPTesorosOcultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendingBadConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEquiparTesoro)
                    .addComponent(jBDescartarTesoro)
                    .addComponent(jBRobarTesoro)
                    .addComponent(jBDescartarTodos))
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDescartarTesoro;
    private javax.swing.JButton jBDescartarTodos;
    private javax.swing.JButton jBEquiparTesoro;
    private javax.swing.JButton jBRobarTesoro;
    private javax.swing.JCheckBox jCBJugadorSectario;
    private javax.swing.JLabel jLBonusBasico;
    private javax.swing.JLabel jLBonusEspecial;
    private javax.swing.JLabel jLEnemigo;
    private javax.swing.JLabel jLJugadorSectario;
    private javax.swing.JLabel jLNivelJugador;
    private javax.swing.JLabel jLNombreJugador;
    private javax.swing.JPanel jPDatosJugador;
    private javax.swing.JPanel jPTesorosOcultos;
    private javax.swing.JPanel jPTesorosVisibles;
    private javax.swing.JTextField jTBonusBasico;
    private javax.swing.JTextField jTBonusEspecial;
    private javax.swing.JTextField jTEnemigo;
    private javax.swing.JTextField jTNivelJugador;
    private javax.swing.JTextField jTNombreJugador;
    private gui.PendingBadConsequenceView pendingBadConsequenceView;
    // End of variables declaration//GEN-END:variables
}
