package gui;

import napakalaki.Prize;

/**
 *
 * @author Carlos de al Torre
 */
public class PrizeView extends javax.swing.JPanel {

    /**
     * Este será el objeto de tipo Prize que tengamos en la vista
     * para preguntarle todos los datos necesarios.
     */
    Prize prizeModel;
    
    /**
     * Creates new form PrizeView
     */
    public PrizeView() {
        initComponents();
    }

    /**
     * Con este metodo conseguimos asignar el Prize a la vista
     * para mostrar todos sus atributos.
     * @param aPrice es un objeto Prize que lo pedimos al controlador.
     */
    protected void setPrize(Prize aPrice){
        this.prizeModel = aPrice;
        
        repaint();
        revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder("Ganancias"));
        setMinimumSize(new java.awt.Dimension(150, 230));
        setPreferredSize(new java.awt.Dimension(150, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
