package gui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import napakalaki.Treasure;

/**
 *
 * @author Carlos de al Torre
 */
public class TreasureView extends javax.swing.JPanel {

    /**
     * Este es el tesoro que nos pasa el controlador con todos los datos del
     * mismo para poser pintarlo
     */
    private Treasure treasureModel;
    /**
     * Esta será la imgen del tesoro
     */
    private Image imagenTesoro;

    /**
     * Creamos un Objeto de tipo Tesoro para la vista.
     */
    public TreasureView() {
        initComponents();
    }

    /**
     * Asignamos el tésoro del modelo a la vista.
     * @param aTreasure este será el tesoro que se mostrará
     */
    protected void setTreasure(Treasure aTreasure) {
        this.treasureModel = aTreasure;
        this.jTANombreTesoro.setText(treasureModel.getName());
        this.jTTipo.setText(treasureModel.getType().name());
        this.jTBonus_Tesoro.setText(""+treasureModel.getMaxBonus());
        this.jTMonedas.setText(""+treasureModel.getGoldCoins());
        try {
            this.imagenTesoro = (new ImageIcon(getClass().getClassLoader().getResource("resources/Tesoros/" + treasureModel.getName() + ".png"))).getImage();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La imagen resources/Tesoros/" + treasureModel.getName()
                    + ".png no está disponible.\n"
                    + "Contactar con los programadores para subsanar el fallo: " + e.getMessage(), "Error!!!", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLMonedas = new javax.swing.JLabel();
        jTMonedas = new javax.swing.JTextField();
        jLBonus = new javax.swing.JLabel();
        jTBonus_Tesoro = new javax.swing.JTextField();
        jLTipo = new javax.swing.JLabel();
        jTTipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTANombreTesoro = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setName("TreasureView"); // NOI18N
        setPreferredSize(new java.awt.Dimension(140, 200));

        jLMonedas.setLabelFor(jTMonedas);
        jLMonedas.setText("Monedas:");

        jTMonedas.setEditable(false);
        jTMonedas.setText("jTMonedas");
        jTMonedas.setBorder(null);

        jLBonus.setLabelFor(jTBonus_Tesoro);
        jLBonus.setText("Bonus:");

        jTBonus_Tesoro.setEditable(false);
        jTBonus_Tesoro.setText("jTBonus_Tesoro");
        jTBonus_Tesoro.setBorder(null);

        jLTipo.setLabelFor(jTTipo);
        jLTipo.setText("Tipo:");

        jTTipo.setEditable(false);
        jTTipo.setText("jTTipo");
        jTTipo.setBorder(null);
        jTTipo.setMinimumSize(new java.awt.Dimension(40, 19));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setWheelScrollingEnabled(false);

        jTANombreTesoro.setBackground(new java.awt.Color(238, 238, 238));
        jTANombreTesoro.setColumns(10);
        jTANombreTesoro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTANombreTesoro.setLineWrap(true);
        jTANombreTesoro.setRows(3);
        jTANombreTesoro.setText("Nombre del Tesoro");
        jTANombreTesoro.setToolTipText("Este es el Nombre del Tesoro");
        jTANombreTesoro.setBorder(null);
        jTANombreTesoro.setName("jTANombreTesoro"); // NOI18N
        jScrollPane1.setViewportView(jTANombreTesoro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLMonedas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLBonus)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTBonus_Tesoro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTipo)
                    .addComponent(jTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBonus)
                    .addComponent(jTBonus_Tesoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMonedas)
                    .addComponent(jTMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLBonus;
    private javax.swing.JLabel jLMonedas;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTANombreTesoro;
    private javax.swing.JTextField jTBonus_Tesoro;
    private javax.swing.JTextField jTMonedas;
    private javax.swing.JTextField jTTipo;
    // End of variables declaration//GEN-END:variables
}
